export type SpotifyScope = 
"user-read-private"|
"user-read-email"|
"user-library-read"|
"user-library-modify"|
"user-follow-read"|
"user-follow-modify"|
"playlist-read-collaborative"|
"playlist-read-private"|
"playlist-modify-private"|
"playlist-modify-public"|
"streaming"|
"app-remote-control"|
"user-read-currently-playing"|
"user-modify-playback-state"|
"user-read-playback-state"|
"user-read-playback-position"|
"user-top-read"|
"user-read-recently-played"|
"ugc-image-upload";